apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: express-app-{{PR_BRANCH}}
  annotations:
    # Nginx Ingress Controller canary annotations for header-based routing
    # This ingress will route traffic when x-multi-env header matches the PR branch name
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "100"
    nginx.ingress.kubernetes.io/canary-by-header: "x-multi-env"
    nginx.ingress.kubernetes.io/canary-by-header-value: "{{PR_BRANCH}}"
spec:
  ingressClassName: nginx
  rules:
  - host: your-domain.com  # Change this to your actual domain
    http:
      paths:
      # Route requests with x-multi-env: {{PR_BRANCH}} header to {{PR_BRANCH}} service
      - path: /
        pathType: Prefix
        backend:
          service:
            name: express-app-{{PR_BRANCH}}
            port:
              number: 80

