{{- if .Values.default.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "express-app.default.ingressName" . }}
  annotations:
    # Default ingress routes traffic when no PR branch header matches
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: {{ .Values.global.ingressClassName }}
  rules:
  - host: {{ .Values.global.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "express-app.default.serviceName" . }}
            port:
              number: {{ .Values.default.service.port }}
{{- end }}

{{- range $prBranch, $prConfig := .Values.prBranches }}
{{- if $prConfig.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "express-app.pr.ingressName" (dict "Values" $.Values "Release" $.Release "Chart" $.Chart "prBranch" $prBranch) }}
  annotations:
    # Nginx Ingress Controller canary annotations for header-based routing
    # This ingress routes traffic when x-multi-env header matches the PR branch name
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "100"
    nginx.ingress.kubernetes.io/canary-by-header: "x-multi-env"
    nginx.ingress.kubernetes.io/canary-by-header-value: {{ $prBranch | quote }}
spec:
  ingressClassName: {{ $.Values.global.ingressClassName }}
  rules:
  - host: {{ $.Values.global.host }}
    http:
      paths:
      # Route requests with x-multi-env: {{ $prBranch }} header to this PR service
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "express-app.pr.serviceName" (dict "Values" $.Values "Release" $.Release "Chart" $.Chart "prBranch" $prBranch) }}
            port:
              number: {{ $prConfig.service.port | default $.Values.default.service.port }}
{{- end }}
{{- end }}

