apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
data:
  nginx.conf: |
    events {
      worker_connections 1024;
    }
    
    http {
      # Default upstream (fallback)
      upstream default {
        server express-app-default:80;
      }
      
      # Include all upstream definitions from separate files
      # Each PR can add its own upstream definition
      include /etc/nginx/conf.d/upstreams/*.conf;
      
      # Main server block
      server {
        listen 80;
        server_name _;
        
        location / {
          # Default upstream
          set $upstream "default";
          
          # Include all routing rules from separate files
          # Each PR can add its own routing rule
          include /etc/nginx/conf.d/routes/*.conf;
          
          # Proxy to the selected upstream
          proxy_pass http://$upstream;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
        
        # Health check endpoint
        location /nginx-health {
          access_log off;
          return 200 "healthy\n";
          add_header Content-Type text/plain;
        }
      }
    }

